### ISSUE TITLE
auto split  large  file

### ISSUE THREAD

**Issue by ChitaGideon** [CleasbyCode/jdvrif#1]
How can I split a large file (2g~) and generate multiple images  into specific size (30M)  with this tool ？

**Comment by CleasbyCode** [comment]
The way this little program currently works it that it embeds and hides a single file (with a current arbitrary limit of 200MB) within a jpg cover image. You can then extract that single hidden file from the cover image. Your single file could be a ZIP/RAR, etc. containing multiple files,  but the program is only going to extract that single ZIP file.  We could easily increase the size limit, but the program is still going to be limited to embedding and extracting single files (of any type).
